img.vimg {
     transition: all 1s   /* 旋转时间为 1s */
}

img.vimg:hover {
     transform: rotate(360deg);
     -webkit-transform: rotate(360deg);
     -moz-transform: rotate(360deg);
     -o-transform: rotate(360deg);
     -ms-transform: rotate(360deg);
}

    -webkit-text-size-adjust: 100%;
    -webkit-tap-highlight-color: transparent;
    letter-spacing: 0.02em;
    --blue: #007bff;
    --indigo: #6610f2;
    --purple: #6f42c1;
    --pink: #e83e8c;
    --red: #dc3545;
    --orange: #fd7e14;
    --yellow: #ffc107;
    --green: #28a745;
    --teal: #20c997;
    --cyan: #17a2b8;
    --white: #fff;
    --gray: #6c757d;
    --gray-dark: #343a40;
    --primary: #007bff;
    --secondary: #6c757d;
    --success: #28a745;
    --info: #17a2b8;
    --warning: #ffc107;
    --danger: #dc3545;
    --light: #f8f9fa;
    --dark: #343a40;
    --breakpoint-xs: 0;
    --breakpoint-sm: 576px;
    --breakpoint-md: 768px;
    --breakpoint-lg: 992px;
    --breakpoint-xl: 1200px;
    --font-family-sans-serif: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans","Liberation Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
    --font-family-monospace: SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;
    --color-mode: "light";
    --body-bg-color: #eee;
    --board-bg-color: #fff;
    --text-color: #3c4858;
    --sec-text-color: #718096;
    --post-text-color: #2c3e50;
    --post-heading-color: #1a202c;
    --post-link-color: #0366d6;
    --link-hover-color: #30a9de;
    --link-hover-bg-color: #f8f9fa;
    --line-color: #eaecef;
    --navbar-bg-color: #2f4154;
    --navbar-text-color: #fff;
    --subtitle-color: #fff;
    --scrollbar-color: #c4c6c9;
    --scrollbar-hover-color: #a6a6a6;
    --button-bg-color: transparent;
    --button-hover-bg-color: #f2f3f5;
    --highlight-bg-color: #f6f8fa;
    --inlinecode-bg-color: rgba(175,184,193,0.2);
    --talking-bg-color: rgba(249, 250, 251, 1);
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    text-align: left;
    font-family: var(--font-family-sans-serif);
    overflow-wrap: break-word;
    color: var(--text-color);
    -webkit-font-smoothing: antialiased;
    box-sizing: border-box;
    vertical-align: middle;
    border-style: none;
    max-width: 100%;
    width: 100%;
    height: 100%;
    border-radius: 50%;
    background-color: transparent;
    object-fit: cover;
    box-shadow: 0 2px 5px 0 rgba(0,0,0,0.16), 0 2px 10px 0 rgba(0,0,0,0.12);